#!/usr/bin/env bash
#
# cluster-setup.sh — interactive setup wizard for the multi-PC HDFS cluster.
#
#   ./cluster-setup.sh             # menu: pick NameNode or DataNode
#   ./cluster-setup.sh namenode    # set up THIS machine as the NameNode (master)
#   ./cluster-setup.sh datanode    # set up THIS machine as a DataNode (worker)
#
# It asks for everything required (IPs, ports, node count, replication),
# generates the config files, builds the copy-to-DataNode bundle, and offers
# to launch the containers.
#
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

NN_IMAGE="bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8"
DN_IMAGE="bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8"
JVM_OPTS="-XX:-UseBiasedLocking -XX:+UseSerialGC -XX:-UsePerfData"

# --- pretty helpers ---------------------------------------------------------
green() { printf '\033[0;32m%s\033[0m\n' "$1"; }
red()   { printf '\033[0;31m%s\033[0m\n' "$1" >&2; }
yellow(){ printf '\033[0;33m%s\033[0m\n' "$1"; }
bold()  { printf '\033[1m%s\033[0m\n' "$1"; }
banner(){ echo; echo "============================================================";
          echo ">> $1"; echo "============================================================"; }

# --- input helpers ----------------------------------------------------------
# All prompts go to stderr so answers can be captured via $().
ask() {
  local prompt="$1" def="${2:-}" ans
  if [[ -n "$def" ]]; then printf '%s [%s]: ' "$prompt" "$def" >&2
  else                     printf '%s: '      "$prompt"       >&2; fi
  read -r ans
  echo "${ans:-$def}"
}

valid_ip() {
  local ip="$1" IFS=. o
  [[ "$ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || return 1
  read -ra o <<< "$ip"
  for n in "${o[@]}"; do (( n <= 255 )) || return 1; done
  return 0
}

ask_ip() {
  local prompt="$1" def="${2:-}" ip
  while true; do
    ip=$(ask "$prompt" "$def")
    valid_ip "$ip" && { echo "$ip"; return; }
    red "  ! '$ip' is not a valid IPv4 address — try again."
  done
}

ask_port() {
  local prompt="$1" def="$2" p
  while true; do
    p=$(ask "$prompt" "$def")
    [[ "$p" =~ ^[0-9]+$ ]] && (( p >= 1 && p <= 65535 )) && { echo "$p"; return; }
    red "  ! port must be a number 1-65535 — try again."
  done
}

ask_int() {
  local prompt="$1" def="$2" min="${3:-1}" max="${4:-}" v
  while true; do
    v=$(ask "$prompt" "$def")
    if [[ "$v" =~ ^[0-9]+$ ]] && (( v >= min )) && { [[ -z "$max" ]] || (( v <= max )); }; then
      echo "$v"; return
    fi
    red "  ! enter a whole number >= $min${max:+ and <= $max} — try again."
  done
}

ask_yes() {  # returns 0 for yes
  local prompt="$1" def="${2:-y}" ans
  ans=$(ask "$prompt (y/n)" "$def")
  [[ "$ans" =~ ^[Yy] ]]
}

detect_lan_ip() {
  local ip=""
  if command -v ipconfig >/dev/null 2>&1; then          # macOS
    for ifc in en0 en1 en2 en3; do
      ip=$(ipconfig getifaddr "$ifc" 2>/dev/null) && [[ -n "$ip" ]] && { echo "$ip"; return; }
    done
  fi
  if command -v hostname >/dev/null 2>&1; then           # most Linux
    ip=$(hostname -I 2>/dev/null | awk '{print $1}')
    [[ -n "$ip" ]] && { echo "$ip"; return; }
  fi
  if command -v ip >/dev/null 2>&1; then                 # Linux fallback
    ip=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')
    [[ -n "$ip" ]] && { echo "$ip"; return; }
  fi
  echo ""
}

backup() { [[ -f "$1" ]] && cp "$1" "$1.bak" && yellow "  (backed up existing $1 -> $1.bak)"; return 0; }

# --- file generators --------------------------------------------------------
write_hadoop_env() {  # nn_ip rpc_port replication
  local nn_ip="$1" rpc_port="$2" repl="$3"
  backup hadoop.env
  cat > hadoop.env <<EOF
# Shared HDFS config — generated by cluster-setup.sh
# bde2020 env->xml naming: '_' -> '.', '___' -> '-'

# Where everyone finds the NameNode (advertised LAN IP, not a docker hostname)
CORE_CONF_fs_defaultFS=hdfs://${nn_ip}:${rpc_port}

# Replication factor (every block copied to this many DataNodes)
HDFS_CONF_dfs_replication=${repl}

# Don't reverse-resolve DataNode IPs to hostnames (cross-host registration)
HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false

# NameNode binds all interfaces but advertises fs.defaultFS host
HDFS_CONF_dfs_namenode_rpc___bind___host=0.0.0.0
HDFS_CONF_dfs_namenode_servicerpc___bind___host=0.0.0.0
HDFS_CONF_dfs_namenode_http___bind___host=0.0.0.0

# Reach DataNodes by their advertised hostname/IP (works through Docker port-publish)
HDFS_CONF_dfs_client_use_datanode_hostname=true
HDFS_CONF_dfs_datanode_use_datanode_hostname=true
EOF
}

write_namenode_compose() {  # nn_ip rpc_port ui_port cluster platform_line
  local nn_ip="$1" rpc_port="$2" ui_port="$3" cluster="$4" platform_line="$5"
  backup docker-compose.namenode.yml
  cat > docker-compose.namenode.yml <<EOF
# Generated by cluster-setup.sh — runs on the NameNode host (${nn_ip}).
#   docker compose -f docker-compose.namenode.yml up -d
services:
  namenode:
    image: ${NN_IMAGE}
    container_name: namenode
    hostname: namenode
${platform_line}    restart: unless-stopped
    ports:
      - "${rpc_port}:${rpc_port}"   # HDFS RPC (DataNodes + clients connect here)
      - "${ui_port}:9870"   # NameNode web UI -> http://${nn_ip}:${ui_port}
    volumes:
      - namenode_data:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: ${cluster}
      HDFS_NAMENODE_OPTS: "${JVM_OPTS}"
      HADOOP_OPTS: "${JVM_OPTS}"
    env_file:
      - ./hadoop.env

volumes:
  namenode_data:
EOF
}

write_datanode_compose() {  # default_dn_host platform_line
  local default_dn="$1" platform_line="$2"
  backup docker-compose.datanode.yml
  cat > docker-compose.datanode.yml <<EOF
# Generated by cluster-setup.sh — runs on EACH DataNode PC. Start it with that
# machine's LAN IP in DN_HOST:
#   DN_HOST=<this-pc-lan-ip> docker compose -f docker-compose.datanode.yml up -d
# Needs the same hadoop.env file next to it.
services:
  datanode:
    image: ${DN_IMAGE}
    container_name: datanode
    hostname: datanode
${platform_line}    restart: unless-stopped
    ports:
      - "9864:9864"   # DataNode web UI
      - "9866:9866"   # data transfer (clients read/write blocks here)
      - "9867:9867"   # DataNode IPC
    volumes:
      - datanode_data:/hadoop/dfs/data
    environment:
      # Advertise THIS host's LAN IP so the NameNode/clients reach the data ports.
      HDFS_CONF_dfs_datanode_hostname: "\${DN_HOST:-${default_dn}}"
      HADOOP_OPTS: "${JVM_OPTS}"
    env_file:
      - ./hadoop.env

volumes:
  datanode_data:
EOF
}

write_check_cluster() {  # nn_ip ui_port  dn_ip...
  local nn_ip="$1" ui_port="$2"; shift 2
  local dn_ips=("$@")
  backup check-cluster.sh
  {
    cat <<EOF
#!/usr/bin/env bash
# check-cluster.sh — generated by cluster-setup.sh. Run on the NameNode host (${nn_ip}).
#   ./check-cluster.sh        # run every step
#   ./check-cluster.sh -p     # pause for <Enter> between steps
set -uo pipefail

NN_CONTAINER="namenode"
NN_IP="${nn_ip}"
NN_UI_PORT="${ui_port}"
# Expected DataNode LAN IPs (only DISPLAYED + counted; never connected to).
DN_IPS=($(printf '"%s" ' "${dn_ips[@]}"))
EOF
    cat <<'BODY'
EXPECTED_DN=${#DN_IPS[@]}
PAUSE=0
[[ "${1:-}" == "-p" ]] && PAUSE=1

green() { printf '\033[0;32m%s\033[0m\n' "$1"; }
red()   { printf '\033[0;31m%s\033[0m\n' "$1"; }
yellow(){ printf '\033[0;33m%s\033[0m\n' "$1"; }
step()  { echo; echo "============================================================";
          echo ">> STEP $1: $2";
          echo "============================================================"; }
pause() { [[ $PAUSE -eq 1 ]] && { read -rp "  [Enter] for next step... " _; }; return 0; }
hdfs()  { docker exec "$NN_CONTAINER" bash -c "$1" 2>/dev/null; }

step 1 "Is the NameNode container running?"
if docker ps --filter "name=^${NN_CONTAINER}$" --format '{{.Names}}' | grep -q "$NN_CONTAINER"; then
  green "OK  - container '$NN_CONTAINER' is up"
  docker ps --filter "name=^${NN_CONTAINER}$" --format '      {{.Status}} | {{.Ports}}'
else
  red "FAIL - NameNode not running. Start it with:"
  echo "        docker compose -f docker-compose.namenode.yml up -d"
  exit 1
fi
pause

step 2 "Is the NameNode web UI responding? (http://${NN_IP}:${NN_UI_PORT})"
code=$(curl -s -o /dev/null -w '%{http_code}' "http://${NN_IP}:${NN_UI_PORT}/" || echo 000)
if [[ "$code" == "200" ]]; then green "OK  - UI returned HTTP 200"
else red "WARN - UI returned HTTP $code (NameNode may still be starting)"; fi
pause

step 3 "Are the DataNodes connected? (expecting ${EXPECTED_DN}: ${DN_IPS[*]})"
report=$(hdfs "hdfs dfsadmin -report" 2>/dev/null)
live=$(echo "$report" | grep -oE 'Live datanodes \(([0-9]+)\)' | grep -oE '[0-9]+' | head -1)
live=${live:-0}
echo "$report" | grep -E 'Live datanodes|^Hostname:|^Name:|Last contact' | sed 's/^/      /'
if [[ "$live" -ge "$EXPECTED_DN" ]]; then
  green "OK  - $live live datanode(s) connected (expected $EXPECTED_DN)"
elif [[ "$live" -ge 1 ]]; then
  yellow "WARN - only $live of $EXPECTED_DN expected datanodes are live"
  echo "        On each missing PC run (with that machine's LAN IP):"
  echo "        DN_HOST=<that-pc-ip> docker compose -f docker-compose.datanode.yml up -d"
else
  red "FAIL - 0 live datanodes. On each DataNode PC run (with its LAN IP):"
  echo "        DN_HOST=<that-pc-ip> docker compose -f docker-compose.datanode.yml up -d"
  yellow "Stopping here - upload test needs a live datanode."
  exit 1
fi
pause

step 4 "Upload a file into HDFS"
hdfs '
echo "hello from multi-pc hdfs cluster - $(date)" > /tmp/hello.txt &&
hdfs dfs -mkdir -p /lab &&
hdfs dfs -put -f /tmp/hello.txt /lab/hello.txt &&
echo "      uploaded /lab/hello.txt"
' && green "OK  - upload succeeded" || { red "FAIL - upload failed"; exit 1; }
pause

step 5 "List and read the file back"
hdfs 'echo "      --- ls /lab ---"; hdfs dfs -ls /lab; echo "      --- cat ---"; hdfs dfs -cat /lab/hello.txt'
pause

step 6 "Prove the block is replicated across the DataNodes (${DN_IPS[*]})"
fsck=$(hdfs "hdfs fsck /lab/hello.txt -files -blocks -locations" 2>/dev/null)
echo "$fsck" | grep -E "DatanodeInfoWithStorage|Status:|Total blocks|repl" | sed 's/^/      /'
if echo "$fsck" | grep -q "Status: HEALTHY"; then
  green "OK  - block is HEALTHY across the live DataNodes (${DN_IPS[*]})"
  if echo "$fsck" | grep -qiE "Under-replicated blocks:[[:space:]]*[1-9]"; then
    yellow "NOTE - some blocks under-replicated: fewer than $EXPECTED_DN datanodes were live at write time."
  fi
else
  yellow "WARN - block not reported HEALTHY"
fi

echo
green "===== Cluster check complete ====="
BODY
  } > check-cluster.sh
  chmod +x check-cluster.sh
}

build_bundle() {
  # Bundle the wizard too, so each DataNode PC needs only this one file.
  tar -czf datanode-bundle.tgz hadoop.env docker-compose.datanode.yml cluster-setup.sh
  green "  wrote datanode-bundle.tgz  (hadoop.env + docker-compose.datanode.yml + cluster-setup.sh)"
}

docker_ready() {
  command -v docker >/dev/null 2>&1 || { yellow "docker not found on PATH — skipping auto-start."; return 1; }
  docker info >/dev/null 2>&1 || { yellow "docker daemon not reachable — skipping auto-start."; return 1; }
  return 0
}

# --- NameNode flow ----------------------------------------------------------
setup_namenode() {
  banner "Set up this machine as the NameNode (master)"
  local nn_ip rpc_port ui_port cluster ndn repl platform_line
  nn_ip=$(ask_ip   "NameNode LAN IP (advertised to DataNodes/clients)" "$(detect_lan_ip)")
  rpc_port=$(ask_port "HDFS RPC port (DataNodes/clients connect here)" 9000)
  ui_port=$(ask_port  "NameNode web UI port"                          9870)
  cluster=$(ask       "Cluster name"                                  "test")
  ndn=$(ask_int       "How many DataNodes will join?"                 3 1)

  local dn_ips=() i
  echo >&2
  yellow "Enter each DataNode's LAN IP (the IP of that physical PC):"
  for (( i=1; i<=ndn; i++ )); do
    dn_ips+=( "$(ask_ip "  DataNode $i LAN IP" "")" )
  done

  local repl_def=$(( ndn < 3 ? ndn : 3 ))
  repl=$(ask_int "Replication factor (1-$ndn; how many copies of each block)" "$repl_def" 1 "$ndn")

  if ask_yes "Pin images to linux/amd64? (needed on Apple Silicon; harmless on x86)" "y"; then
    platform_line=$'    platform: linux/amd64\n'
  else
    platform_line=''
  fi

  banner "Generating config files"
  write_hadoop_env       "$nn_ip" "$rpc_port" "$repl"
  write_namenode_compose "$nn_ip" "$rpc_port" "$ui_port" "$cluster" "$platform_line"
  write_datanode_compose "${dn_ips[0]}" "$platform_line"
  write_check_cluster    "$nn_ip" "$ui_port" "${dn_ips[@]}"
  build_bundle
  green "  wrote hadoop.env, docker-compose.namenode.yml, docker-compose.datanode.yml, check-cluster.sh"

  banner "Summary"
  echo "  NameNode        : ${nn_ip}  (RPC ${rpc_port}, UI http://${nn_ip}:${ui_port})"
  echo "  DataNodes (${ndn})  : ${dn_ips[*]}"
  echo "  Replication     : ${repl}"
  echo "  Cluster name    : ${cluster}"

  echo
  if docker_ready && ask_yes "Start the NameNode now (docker compose up -d)?" "y"; then
    docker compose -f docker-compose.namenode.yml up -d
    green "NameNode starting. Watch it with:  docker logs -f namenode"
    echo  "UI: http://${nn_ip}:${ui_port}"
  fi

  banner "Next steps — on each DataNode PC"
  echo "  1. Copy datanode-bundle.tgz to the PC, then unpack:  tar -xzf datanode-bundle.tgz"
  echo "  2. Run:                                             ./cluster-setup.sh datanode"
  echo "     (or manually:  DN_HOST=<that-pc-ip> docker compose -f docker-compose.datanode.yml up -d )"
  echo "  3. Back here, verify:                               ./check-cluster.sh"
}

# --- DataNode flow ----------------------------------------------------------
setup_datanode() {
  banner "Set up this machine as a DataNode (worker)"
  local dn_host platform_line

  # Prefer the hadoop.env shipped from the NameNode (keeps fs.defaultFS + replication identical).
  if [[ -f hadoop.env ]] && grep -q '^CORE_CONF_fs_defaultFS=' hadoop.env; then
    local cur; cur=$(grep '^CORE_CONF_fs_defaultFS=' hadoop.env | cut -d= -f2-)
    yellow "Found hadoop.env (NameNode = ${cur})."
    if ! ask_yes "Use this existing hadoop.env (recommended if copied from the NameNode)?" "y"; then
      regen_datanode_env
    fi
  else
    yellow "No hadoop.env here — let's create one pointing at the NameNode."
    regen_datanode_env
  fi

  dn_host=$(ask_ip "THIS PC's LAN IP (DN_HOST — how the NameNode reaches this node)" "$(detect_lan_ip)")

  if ask_yes "Pin image to linux/amd64? (needed on Apple Silicon; harmless on x86)" "y"; then
    platform_line=$'    platform: linux/amd64\n'
  else
    platform_line=''
  fi

  banner "Generating DataNode config"
  write_datanode_compose "$dn_host" "$platform_line"
  green "  wrote docker-compose.datanode.yml (advertises ${dn_host})"

  echo
  if docker_ready && ask_yes "Start this DataNode now?" "y"; then
    DN_HOST="$dn_host" docker compose -f docker-compose.datanode.yml up -d
    green "DataNode starting. Watch it with:  docker logs -f datanode"
    echo  "It will register with the NameNode and start sending heartbeats."
  else
    echo "Start it later with:"
    echo "  DN_HOST=${dn_host} docker compose -f docker-compose.datanode.yml up -d"
  fi
}

regen_datanode_env() {
  local nn_ip rpc_port repl
  nn_ip=$(ask_ip     "NameNode LAN IP"  "")
  rpc_port=$(ask_port "NameNode RPC port" 9000)
  repl=$(ask_int     "Replication factor (must match the cluster)" 3 1)
  write_hadoop_env "$nn_ip" "$rpc_port" "$repl"
  green "  wrote hadoop.env -> hdfs://${nn_ip}:${rpc_port} (replication ${repl})"
}

# --- entry point ------------------------------------------------------------
main() {
  bold "HDFS multi-PC cluster setup"
  case "${1:-}" in
    namenode|nn|master|1) setup_namenode ;;
    datanode|dn|worker|2) setup_datanode ;;
    -h|--help|help)
      echo "Usage: $0 [namenode|datanode]   (no argument => interactive menu)"; exit 0 ;;
    "")
      echo
      echo "What role is THIS machine?"
      echo "  1) NameNode (master — runs the cluster, one per cluster)"
      echo "  2) DataNode (worker  — stores blocks, one per PC)"
      case "$(ask "Select 1 or 2" "")" in
        1|namenode|nn|master) setup_namenode ;;
        2|datanode|dn|worker) setup_datanode ;;
        *) red "Invalid choice."; exit 1 ;;
      esac ;;
    *) red "Unknown role '$1'. Use: namenode | datanode"; exit 1 ;;
  esac
}

main "$@"
